[22기 이윤경] Login 페이지 레이아웃 + Validation 기능 구현 완료하였습니다!
wecode-bootcamp-korea/22-1st-Villy-frontend pull request #5
Opened 2021-07-06 13:52 UTC by leeykyk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
✔Login 페이지 레이아웃 구현 완료
✔Validation 기능 구현 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
✔ id '@' 포함, password 6 글자 이상 입력 시 버튼 활성화

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
✔fetch 함수는 일단 추가해 놓기만 했습니다! 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-07 02:56 UTC, younuk23 reviewed
리뷰 확인해주세요!

2021-07-07 02:56 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    return <div></div>;
수정할 필요 없어보입니다!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.js
> +          localStorage.setItem('access_token :', result.token);
```suggestion
          localStorage.setItem('access_token', result.token);
```
localStorage에 저장할 토큰의 키값에 굳이 `:` 는 들어갈 필요 없어보입니다!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.js
> +        if (result.token !== undefined) {
undefined는 falsy값이니까 굳이 !== 로 비교해줄 필요 없어보입니다!
```suggestion
        if (result.token) {
```

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.js
> +      <div className="login_view">
div 보다 적합한 태그가 있어보입니다!
그리고 이 컴포넌트에서 className에 snake_case를 사용하셨는데 
물론 className에 camelCase를 사용해도되고 snake_case를 사용해도 됩니다!
다만, 팀원 전체적으로 하나의 case를 작성해줘야 추후 다른 팀원들도 같이 보기가 좋겠죠?
팀원들과 협의해서 className snake_case로 할건지, camelCase로 할건지 결정해서 통일해주세요!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.js
> +          <img alt="로그인 logo" src="../images/logo.png"></img>
- image 파일은 public에서 관리해주세요!
- 셀프 클로징 적용해주세요!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.js
> +            id="userId"
id selector는 사용을 지양해주세요!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.js
> +                userId.includes('@') && userPw.length > 4 ? false : true
```suggestion
                !(userId.includes('@') && userPw.length > 4)
```
굳이 삼항연산자 사용 안해도 될 것 같습니다!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.js
> +  loginFetch = () => {
loginFetch라는 변수명보다는 requestLogin 등의 이름이 좀 더 맞지 않을까요? Fetch라는 이름은 좀 좋지않아보입니다!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.scss
> +}
body에 특정 스타일을 주는건 지양해주세요!
SPA의 특성 상 전체 페이지에 영향을 미치게 됩니다!
만약 정말로 body에 스타일을 공통으로 적용시켜야 된다면 common.scss에 적용하시는게 맞아보입니다!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.scss
> +  display: block;
div는 이미 block속성을 가지고 있는데 다시 display:block을 줄 이유가 없어보입니다

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.scss
> +  flex-direction: column;
display:flex가 없는데 flex-direction 속성을 왜 부여하신걸까요? 의미없는 부분같아보입니다!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.scss
> +  .logo img {
다른 선택자들끼리는 공백 주세요

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.scss
> +    }
동일한 속성이 반복되는데 하나의 클레스네임에 해당 속성 부여하고 그 클래스네임을 각 태그한테 부여하는게 좋아보입니다!

2021-07-07 02:56 UTC, younuk23 commented on src/pages/Login/Login.scss
> +  }
태그 셀렉터 지양해주세요!

2021-07-07 04:01 UTC, leeykyk commented on src/components/Nav/Nav.js
> +    return <div></div>;
화긴 완료!!! 👀

2021-07-07 04:03 UTC, leeykyk commented on src/pages/Login/Login.js
> +          localStorage.setItem('access_token :', result.token);
수정 완료하였습니다!! 😎

2021-07-07 04:05 UTC, leeykyk commented on src/pages/Login/Login.js
> +        if (result.token !== undefined) {
수정 완료하였습니다!! 😎

2021-07-07 04:13 UTC, leeykyk commented on src/pages/Login/Login.js
> +      <div className="login_view">
그부분은 미처 파악하지 못했던 부분이었습니다!! 팀원들과 camelCase로 하기로했습니다!! :)
피드백 감사합니다~~!! 😃

2021-07-07 06:49 UTC, leeykyk commented on src/pages/Login/Login.js
> +          <img alt="로그인 logo" src="../images/logo.png"></img>
수정 완료!!😎

2021-07-07 06:51 UTC, leeykyk commented on src/pages/Login/Login.js
> +            id="userId"
넵!!! 수정 완료!!😎

2021-07-07 06:56 UTC, leeykyk commented on src/pages/Login/Login.js
> +                userId.includes('@') && userPw.length > 4 ? false : true
수정 완료!! 연욱님 덕분에 많이 배웁니다!! 🙏🏻

2021-07-07 07:08 UTC, leeykyk commented on src/pages/Login/Login.js
> +  loginFetch = () => {
변경 완료!!!😃

2021-07-07 07:09 UTC, leeykyk commented on src/pages/Login/Login.scss
> +}
확인 완료!! 수정 완료!!! 😎 감사합니당!!

2021-07-07 07:19 UTC, leeykyk commented on src/pages/Login/Login.scss
> +  display: block;
맨날 까먹네요 ㅠㅠㅠ 수정 완료!! 😃

2021-07-07 07:21 UTC, leeykyk commented on src/pages/Login/Login.scss
> +  flex-direction: column;
앗 정신없이 코딩하다보니 제대로 정리를 안했나봅니다. 수정 완료!! 감사합니다!! 😃

2021-07-07 07:21 UTC, leeykyk commented on src/pages/Login/Login.scss
> +  .logo img {
수정 완료!!😃

2021-07-07 07:35 UTC, leeykyk commented on src/pages/Login/Login.scss
> +    }
수정 완료!!😃

2021-07-07 07:38 UTC, leeykyk commented on src/pages/Login/Login.scss
> +  }
이걸 지우면...nesting이 안되여..유유😭

2021-07-08 05:09 UTC, younuk23 reviewed
리뷰 확인 및 반영해주세요~!

2021-07-08 05:09 UTC, younuk23 commented on src/pages/Login/Login.js
> +          <div className="loginImg">
div에 logimImg라는 명칭은 조금 부적합한 것 같습니다 logoWrapper 등이 어떨까요?

2021-07-08 05:09 UTC, younuk23 commented on src/pages/Login/Login.scss
> +    }
잘 활용하셨네요! 다만 이 경우에는 기본적으로 적용되어야 하는 속성이 정해져있고 거기에 확장하는 형식이기에 extends 기능을 활용하는것도 좋아보입니다!

2021-07-08 05:09 UTC, younuk23 commented on src/pages/Login/Login.scss
> +    }
sass 공식문서에서 extend 기능 한번 확인해보세요!

2021-07-08 05:09 UTC, younuk23 commented on src/pages/Login/Login.js
> +          <div className="loginForm">
여기는 div보다는 form tag가 적합하지 않을까요?

2021-07-08 05:36 UTC, leeykyk commented on src/pages/Login/Login.js
> +          <div className="loginImg">
수정 완료!!😎

2021-07-09 06:04 UTC, younuk23 reviewed
마이너한 수정이라서 금방 반영될 것 같네요!
윤경님 브랜치 잘 나눠서 작업하시는것 너무 좋네요👍
브랜치 잘 나누셔서 작업해서 수정사항도 금방금방 반영되고 머지도 빨리 될 것 같습니다!
코멘트 드린 사항만 수정해주세요!

2021-07-09 06:04 UTC, younuk23 commented on src/pages/Login/Login.js
> +    fetch('http://10.58.5.217:8000/users/signin', {
api 주소는 `config.js` 에서 관리하는 것으로 수정해주세요-!

API는 `config.js` 파일에서 일괄적으로 관리하면서 import, export 를 통해 사용하는 식으로 관리하는 것이 좋습니다. 그렇지 않을 경우, 백엔드 서버 IP 가 변경되면 fetch 함수를 일일이 찾아서 API 를 직접 수정해 주어야 하기 때문입니다.

`config.js` 에서 관리를 하면서 import / export 를 사용하면 아래와 같이 구성이 될 것입니다.

```jsx
// src/config.js
const BASE_URL = 'http://10.58.5.151:8000'
export const GET_PRODUCT_API = `${BASE_URL}/products`

// 사용하는 컴포넌트
import { GET_PRODUCT_API } from '../../../config.js';

...

fetch(`${GET_PRODUCT_API}/5`).then(...).then(...);
```

위의 경우, 백엔드 IP 가 바뀔 때 `config.js` 에서 IP 만 바꾸어주면 모든 API 가 새로운 IP 에 따라서 변경됩니다. 그렇기 때문에 일일이 fetch 함수를 찾아 API 를 수정해줄 필요가 없습니다.

2021-07-09 06:04 UTC, younuk23 commented on src/pages/Login/Login.js
> +    fetch('http://10.58.5.217:8000/users/signin', {
팀원들한테도 공유해서 api 주소 사용할 일 있으면 전체적으로 이렇게 사용하도록 통일해주세요!

2021-07-09 06:04 UTC, younuk23 commented on src/pages/Login/Login.js
> +              src="http://localhost:3000/images/logo.png"
```suggestion
              src="/images/logo.png"
```
http://localhost:3000 기입하실 필요 없습니다!

2021-07-09 10:23 UTC, younuk23 approved these changes
LGTM

2021-07-09 10:24 UTC, younuk23 requested changes
Conflict 해결해주세요!

2021-07-12 01:40 UTC, younuk23 approved these changes
LGTM

2021-07-12 01:40 UTC, merged