[22기 이윤경] Cart 페이지 레이아웃 구현 완료하였습니다!
wecode-bootcamp-korea/22-1st-Villy-frontend pull request #7
Opened 2021-07-08 02:59 UTC by leeykyk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
✔ Cart 레이아웃 구현 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
✔ 레이아웃 구현 완료
✔ 코드 리팩토링은 아직 진행하지 않았습니다!

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
✔ 아직은 없습니다!!!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-08 05:31 UTC, younuk23 reviewed
리뷰 확인 및 반영해주세요

2021-07-08 05:31 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +          <div className="cartTop">
h1~h6 요소를 감싸는 태그는 div 보다 적합한 태그가 있습니다!

2021-07-08 05:31 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +            <img alt="이미지" src="http://localhost:3000/images/pill1.jpeg" />
```suggestion
            <img alt="이미지" src="/images/pill1.jpeg" />
```
localhost:3000까지는 안적어줘도 됩니다. 안적어주면 현재 실행중인 서버주소로 자동으로 인식됩니다.
오히려 3000포트를 임의적으로 적어주게 되면 추후 3001포트, 3002포트등에서 실행됬을 경우 이미지가 제대로 안 불러와질 수 있습니다.

2021-07-08 05:31 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +            <img alt="이미지" src="http://localhost:3000/images/pill1.jpeg" />
alt에 이미지라고 적는것은 좋지 않습니다!
이미 img tag이기 때문에 이미지인것은 알 수 있습니다. 무슨 이미지인지 표현해주세요! e.g.) alt="약"

2021-07-08 05:31 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +  h2 {
tag selector는 다른 요소들에 영향을 미칠 여지가 많기때문에 지양해주세요!

2021-07-08 05:31 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +            <div className="cartTopBtn">
div는 Button이 아닌데 Btn이란 이름을 쓰는건 적절치 않아보입니다!
cartButtonWrppaer 등이 어떨까요?

2021-07-08 05:31 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +        .listFont {
다른 선택자들끼리 공백주세요

2021-07-08 05:31 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +          padding-bottom: 20px;
이미 padding:20px인데 padding-bottom을 다시 20px을 줄 이유가 없어보입니다!
윤경님 전반적으로 css가 작성순서 컨벤션도 안맞고 필요없는 속성 부여한 부분이 많아보이는데 한번씩 확인해보시면 좋을 것 같습니다~!

2021-07-08 06:48 UTC, leeykyk commented on src/pages/Cart/Cart.js
> +            <img alt="이미지" src="http://localhost:3000/images/pill1.jpeg" />
수정 완료!!😎

2021-07-08 06:56 UTC, leeykyk commented on src/pages/Cart/Cart.scss
> +  h2 {
수정 완료!!

2021-07-08 06:58 UTC, leeykyk commented on src/pages/Cart/Cart.js
> +            <div className="cartTopBtn">
수정 완료!!

2021-07-08 07:05 UTC, leeykyk commented on src/pages/Cart/Cart.scss
> +        .listFont {
수정 완료!!!

2021-07-08 07:06 UTC, leeykyk commented on src/pages/Cart/Cart.scss
> +          padding-bottom: 20px;
수정 완료!!

2021-07-08 07:08 UTC, leeykyk commented on src/pages/Cart/Cart.js
> +          <div className="cartTop">
수정 완료!!!

2021-07-09 06:53 UTC, younuk23 reviewed
scss 속성순서만 다시 한번 보시고, mixin 활용 해보시면 좋을 것 같습니다!

2021-07-09 06:53 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +    flex-direction: column;
flex랑 flex-direction이 붙어있는게 좀 더 보기좋지 않을까요?

2021-07-09 06:53 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +        height: 100px;
이미지의 경우 width나 height중에 한가지만 지정해도 원본 이미지의 비율에 맞게 나머지 값이 조정됩니다!

2021-07-09 06:53 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +        justify-content: space-between;
mixin 활용하시는것도 좋겠네요!

2021-07-09 07:12 UTC, leeykyk commented on src/pages/Cart/Cart.scss
> +    flex-direction: column;
수정 완료!!!😃

2021-07-09 07:13 UTC, leeykyk commented on src/pages/Cart/Cart.scss
> +        height: 100px;
해보니까 그렇게 안돼서 둘다 지정해줬습니다ㅠㅠㅠㅠㅠㅠ😭

2021-07-09 07:15 UTC, leeykyk commented on src/pages/Cart/Cart.scss
> +        justify-content: space-between;
```
.countButtonWrppaer {
  @include display-flex;
```

수정 완료!!!

2021-07-09 10:32 UTC, younuk23 approved these changes
Approve

2021-07-09 10:32 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +@import '../../styles/common.scss';
common.scss는 index.js에서 import 하고있으니까 여기서 import 할 필요 없어보입니다!
이거 빼고는 문제 없어서 일단 머지하겠습니다!
다음 브랜치에서 이거 꼭 삭제해주세요!

2021-07-09 10:33 UTC, younuk23 commented on src/pages/Cart/Cart.scss
> +@import '../../styles/common.scss';
컨플릭트 해결하셔야되네요 해결하시면서 이거 수정해주세요!

2021-07-09 10:33 UTC, younuk23 requested changes
Request Change

2021-07-09 11:14 UTC, leeykyk commented on src/pages/Cart/Cart.scss
> +@import '../../styles/common.scss';
수정 완료!!😃

2021-07-12 01:46 UTC, younuk23 commented
Conflict 해결해주세요!

2021-07-12 01:57 UTC, leeykyk commented
> Conflict 해결해주세요!

원인이 common.scss의 변수 문제였는데 세팅할 때 잘못 넣은거라 ... 팀원끼리 협의해서 전부 변경했습니다!!

2021-07-12 08:12 UTC, younuk23 approved these changes
LGTM

2021-07-12 08:15 UTC, merged